<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminAreasDependenciasSeeder extends Seeder {
  /**
   * Ejecuta el seeder de la tabla areas_dependencias
   * de la base de datos de administración.
   *
   * @return void
   */
  public function run() {
    DB::table('areas_dependencias')->insert([
      ['id' =>   1, 'id_dependencia' =>	11,	'id_area' => 21],
      ['id' =>   2, 'id_dependencia' =>	11,	'id_area' => 37],
      ['id' =>   3, 'id_dependencia' =>	11,	'id_area' => 40],
      ['id' =>   4, 'id_dependencia' =>	11,	'id_area' => 59],
      ['id' =>   5, 'id_dependencia' =>	11,	'id_area' => 69],
      ['id' =>   6, 'id_dependencia' =>	11,	'id_area' => 71],
      ['id' =>   7, 'id_dependencia' =>	11,	'id_area' => 70],
      ['id' =>   8, 'id_dependencia' =>	11,	'id_area' =>  4],
      ['id' =>   9, 'id_dependencia' =>	17,	'id_area' => 73],
      ['id' =>  10, 'id_dependencia' =>	17,	'id_area' => 31],
      ['id' =>  11, 'id_dependencia' =>	17,	'id_area' => 29],
      ['id' =>  12, 'id_dependencia' =>	17,	'id_area' => 33],
      ['id' =>  13, 'id_dependencia' =>	17,	'id_area' => 35],
      ['id' =>  14, 'id_dependencia' =>	17,	'id_area' => 36],
      ['id' =>  15, 'id_dependencia' =>	17,	'id_area' => 42],
      ['id' =>  16, 'id_dependencia' =>	13,	'id_area' => 66],
      ['id' =>  17, 'id_dependencia' =>	13,	'id_area' => 74],
      ['id' =>  18, 'id_dependencia' =>	13,	'id_area' => 57],
      ['id' =>  19, 'id_dependencia' =>	13,	'id_area' => 63],
      ['id' =>  20, 'id_dependencia' =>	13,	'id_area' => 61],
      ['id' =>  21, 'id_dependencia' =>	13,	'id_area' => 56],
      ['id' =>  22, 'id_dependencia' =>	13,	'id_area' => 55],
      ['id' =>  23, 'id_dependencia' =>	13,	'id_area' => 54],
      ['id' =>  24, 'id_dependencia' =>	13,	'id_area' => 62],
      ['id' =>  25, 'id_dependencia' =>	13,	'id_area' => 75],
      ['id' =>  26, 'id_dependencia' =>	13,	'id_area' => 81],
      ['id' =>  27, 'id_dependencia' =>	14,	'id_area' => 48],
      ['id' =>  28, 'id_dependencia' =>	14,	'id_area' =>  7],
      ['id' =>  29, 'id_dependencia' =>	14,	'id_area' => 10],
      ['id' =>  30, 'id_dependencia' =>	14,	'id_area' => 46],
      ['id' =>  31, 'id_dependencia' =>	14,	'id_area' => 50],
      ['id' =>  32, 'id_dependencia' =>	14,	'id_area' => 58],
      ['id' =>  33, 'id_dependencia' =>	14,	'id_area' => 65],
      ['id' =>  34, 'id_dependencia' =>	14,	'id_area' => 67],
      ['id' =>  35, 'id_dependencia' =>	14,	'id_area' => 80],
      ['id' =>  36, 'id_dependencia' =>	15,	'id_area' => 68],
      ['id' =>  37, 'id_dependencia' =>	15,	'id_area' =>  6],
      ['id' =>  38, 'id_dependencia' =>	15,	'id_area' =>  8],
      ['id' =>  39, 'id_dependencia' =>	15,	'id_area' => 30],
      ['id' =>  40, 'id_dependencia' =>	15,	'id_area' => 64],
      ['id' =>  41, 'id_dependencia' =>	16,	'id_area' => 49],
      ['id' =>  42, 'id_dependencia' =>	16,	'id_area' =>  1],
      ['id' =>  43, 'id_dependencia' =>	16,	'id_area' => 26],
      ['id' =>  44, 'id_dependencia' =>	16,	'id_area' => 28],
      ['id' =>  45, 'id_dependencia' =>	16,	'id_area' => 38],
      ['id' =>  46, 'id_dependencia' =>	16,	'id_area' => 39],
      ['id' =>  47, 'id_dependencia' =>	16,	'id_area' => 41],
      ['id' =>  48, 'id_dependencia' =>	 3,	'id_area' =>  5],
      ['id' =>  49, 'id_dependencia' =>	 3,	'id_area' => 76],
      ['id' =>  50, 'id_dependencia' =>	 3,	'id_area' => 77],
      ['id' =>  51, 'id_dependencia' =>	 3,	'id_area' => 78],
      ['id' =>  52, 'id_dependencia' =>	 3,	'id_area' => 79],
      ['id' =>  53, 'id_dependencia' =>	 2,	'id_area' => 23],
      ['id' =>  54, 'id_dependencia' =>	 2,	'id_area' =>  2],
      ['id' =>  55, 'id_dependencia' =>	 2,	'id_area' => 11],
      ['id' =>  56, 'id_dependencia' =>	 2,	'id_area' => 13],
      ['id' =>  57, 'id_dependencia' =>	 2,	'id_area' => 16],
      ['id' =>  58, 'id_dependencia' =>	 2,	'id_area' => 51],
      ['id' =>  59, 'id_dependencia' =>	 2,	'id_area' => 52],
      ['id' =>  60, 'id_dependencia' =>	 4,	'id_area' => 43],
      ['id' =>  61, 'id_dependencia' =>	 5,	'id_area' => 23],
      ['id' =>  62, 'id_dependencia' =>	 5,	'id_area' =>  2],
      ['id' =>  63, 'id_dependencia' =>	 5,	'id_area' => 11],
      ['id' =>  64, 'id_dependencia' =>	 5,	'id_area' => 13],
      ['id' =>  65, 'id_dependencia' =>	 5,	'id_area' => 16],
      ['id' =>  66, 'id_dependencia' =>	 5,	'id_area' => 51],
      ['id' =>  67, 'id_dependencia' =>	 5,	'id_area' => 52],
      ['id' =>  68, 'id_dependencia' =>	 5,	'id_area' =>  3],
      ['id' =>  69, 'id_dependencia' =>	 6,	'id_area' => 44],
      ['id' =>  70, 'id_dependencia' =>	 6,	'id_area' => 15],
      ['id' =>  71, 'id_dependencia' =>	 6,	'id_area' => 17],
      ['id' =>  72, 'id_dependencia' =>	 6,	'id_area' => 22],
      ['id' =>  73, 'id_dependencia' =>	 6,	'id_area' => 27],
      ['id' =>  74, 'id_dependencia' =>	 6,	'id_area' => 32],
      ['id' =>  75, 'id_dependencia' =>	 6,	'id_area' => 34],
      ['id' =>  76, 'id_dependencia' =>	 6,	'id_area' => 24],
      ['id' =>  77, 'id_dependencia' =>	 9,	'id_area' => 45],
      ['id' =>  78, 'id_dependencia' =>	 9,	'id_area' =>  2],
      ['id' =>  79, 'id_dependencia' =>	 9,	'id_area' => 12],
      ['id' =>  80, 'id_dependencia' =>	 9,	'id_area' => 14],
      ['id' =>  81, 'id_dependencia' =>	 9,	'id_area' => 18],
      ['id' =>  82, 'id_dependencia' =>	 9,	'id_area' => 20],
      ['id' =>  83, 'id_dependencia' =>	 9,	'id_area' => 60],
      ['id' =>  84, 'id_dependencia' =>	10,	'id_area' => 47],
      ['id' =>  85, 'id_dependencia' =>	10,	'id_area' =>  9],
      ['id' =>  86, 'id_dependencia' =>	10,	'id_area' => 19],
      ['id' =>  87, 'id_dependencia' =>	10,	'id_area' => 25],
      ['id' =>  88, 'id_dependencia' =>	10,	'id_area' => 53],
      ['id' =>  89, 'id_dependencia' =>	10,	'id_area' => 72],
    ]);

    DB::table('areas_dependencias')->insert([
      ['id' =>  90, 'id_dependencia' =>	12],
      ['id' =>  91, 'id_dependencia' =>	18],
      ['id' =>  92, 'id_dependencia' =>	 1],
      ['id' =>  93, 'id_dependencia' =>	 7],
      ['id' =>  94, 'id_dependencia' =>	 8],
      ['id' =>  95, 'id_dependencia' =>	19],
      ['id' =>  96, 'id_dependencia' =>	20],
      ['id' =>  97, 'id_dependencia' =>	21],
      ['id' =>  98, 'id_dependencia' =>	25],
      ['id' =>  99, 'id_dependencia' =>	22],
      ['id' => 100, 'id_dependencia' =>	23],
      ['id' => 101, 'id_dependencia' =>	24],
      ['id' => 102, 'id_dependencia' =>	26],
      ['id' => 103, 'id_dependencia' =>	28],
      ['id' => 104, 'id_dependencia' =>	29],
      ['id' => 105, 'id_dependencia' =>	30],
      ['id' => 106, 'id_dependencia' =>	27],
    ]);
  }
}
